### PR TITLE
chore: add quick start

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

### CODE REVIEW

**Review by tokers — APPROVED** [review]

**Comment by membphis** [comment]
the ci is unstable, I rerun it

**Comment by membphis** [comment]
https://github.com/api7/apisix-mesh-agent/pull/59/checks?check_run_id=2701174664#step:4:117

@tokers do you know the reason?

**Comment by tokers** [comment]
> https://github.com/api7/apisix-mesh-agent/pull/59/checks?check_run_id=2701174664#step:4:117
> 
> @tokers do you know the reason?

Cannot reproduce on my side.

**Comment by tao12345666333** [comment]
can we merge this? @membphis @tokers

**Comment by tokers** [comment]
@tao12345666333 I'll fix the CI broken problem in another PR.

**Pull request merged**
